<figure>
  <IMG SRC="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Fachhochschule_Südwestfalen_20xx_logo.svg/320px-Fachhochschule_Südwestfalen_20xx_logo.svg.png" WIDTH=250 ALIGN="right">
</figure>

# Einführung Machine Learning
### Sommersemester 2026
Prof. Dr. Heiner Giefers

## Aufgabe: Umgang mit fehlenden Daten

Im folgendem Dataframe fehlen Werte für eine Reihe von Datenpunkten

In [1]:
import pandas as pd
import numpy as np
import datetime

punkte_np = np.array([[5,np.nan,70],[np.nan,5,np.nan],[0, 0, np.nan], [np.nan, 5, 85]])
punkte = pd.DataFrame(punkte_np, columns=["A1", "A2", "T1"], index=["Alice","Bob","Carol","Dave"])
punkte

        A1   A2    T1
Alice  5.0  NaN  70.0
Bob    NaN  5.0   NaN
Carol  0.0  0.0   NaN
Dave   NaN  5.0  85.0

Wir wollen nun die fehlen Werte in den Spalten `A1`, `A2` und `T1` mit sinnvollen Werten auffüllen.
Was sinnvoll ist, hängt natürlich stark davon ab, welche Bedeutung die Spalte für den Datensatz hat und wie die fehlenden Werte zu erklären sind.
Wir wollen hier einmal 3 verschiedene Szenarien am Beispiel einer Übungspunkteliste durchspielen:
- Bei der Spalte `A1` handelt es sich um eine Aufgabe, die von allen Personen eingereicht werden sollte. Fehlende Werte sind also mit Null Punkten zu interpretieren.
- Bei der zweiten Aufgabe (`A2`) konnten nicht alle Personen teilnehmen. Aus Fairnessgründen sollen fehlende Werte hier mit dem arithmetischen Mittelwert aller Ergebnisse aufgefüllt werden.
- Bei der Spalte `T1` handelt es sich um die Bearbeitungszeit einer Aufgabe in Minuten. Leider fehlt bei einigen Personen die Zeitangabe, die Liste ist aber nach Abgabezeitpunkt sortiert. Wir wollen daher die fehlenden Zeiten (linear) interpolieren.

**1. Füllen Sie die fehlenden Werte in Spalte `A1` mit Nullen auf**

In [2]:

punkte['A1'] = punkte['A1'].fillna(0)

#raise NotImplementedError()
punkte

        A1   A2    T1
Alice  5.0  NaN  70.0
Bob    0.0  5.0   NaN
Carol  0.0  0.0   NaN
Dave   0.0  5.0  85.0

**2. Füllen Sie die fehlenden Werte in Spalte `A2` mit dem arithmetischen Mittelwerte aller numerischen Werte der Spalte auf**

In [3]:
# YOUR CODE HERE

punkte['A2'] = punkte['A2'].fillna(punkte['A2'].mean().round(1))

#raise NotImplementedError()
punkte

        A1   A2    T1
Alice  5.0  3.3  70.0
Bob    0.0  5.0   NaN
Carol  0.0  0.0   NaN
Dave   0.0  5.0  85.0

**3. Interpolieren die fehlenden Werte der Spalte `T1` linear**

In [5]:
# YOUR CODE HERE

punkte['T1'] = punkte['T1'].interpolate(method='linear')

#raise NotImplementedError()
punkte

        A1   A2    T1
Alice  5.0  3.3  70.0
Bob    0.0  5.0  75.0
Carol  0.0  0.0  80.0
Dave   0.0  5.0  85.0